-- Most products sold in a day in the last week

SELECT P.PCODE, P.PNAME, MAX(TOTAL_P) AS NO_OF_PURCHASES, S.DOP FROM PRODUCTS P 
INNER JOIN (SELECT SUM(NOU) AS TOTAL_P, PCODE, DOP FROM PURCHASE PR, CUSTOMER C
WHERE PR.CUID = C.CUID AND C.LCODE = '602' AND DOP BETWEEN '2021-01-03' AND '2021-01-11' GROUP BY PCODE) S
ON S.PCODE = P.PCODE;

-- Total products sold by each sales exec

SELECT SE.SEID, SE.SENAME, SE.DOB, SE.GENDER, SE.MOBILE_NO, T.PRODUCTS_SOLD FROM SALES_EXEC SE
LEFT JOIN (SELECT SEID, SUM(P.NOU) AS PRODUCTS_SOLD FROM PURCHASE P GROUP BY SEID) T
ON SE.SEID = T.SEID;